// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetCurrentDuration() {
  return window['go']['main']['App']['GetCurrentDuration']();
}

export function GetDefaultOutputDir() {
  return window['go']['main']['App']['GetDefaultOutputDir']();
}

export function GetEncoders() {
  return window['go']['main']['App']['GetEncoders']();
}

export function GetRecentRecordings() {
  return window['go']['main']['App']['GetRecentRecordings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PauseRecording() {
  return window['go']['main']['App']['PauseRecording']();
}

export function PlayVideo(arg1) {
  return window['go']['main']['App']['PlayVideo'](arg1);
}

export function ResumeRecording() {
  return window['go']['main']['App']['ResumeRecording']();
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function StartRecording(arg1) {
  return window['go']['main']['App']['StartRecording'](arg1);
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function TogglePauseResume() {
  return window['go']['main']['App']['TogglePauseResume']();
}
