// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetAudioDevices():Promise<any>;

export function GetCurrentDuration():Promise<number>;

export function GetDefaultOutputDir():Promise<string>;

export function GetEncoders():Promise<Array<backend.EncoderInfo>>;

export function GetRecentRecordings():Promise<Array<backend.RecordedFileEntry>>;

export function GetStatus():Promise<backend.RecordingStatus>;

export function IsRecording():Promise<boolean>;

export function OpenFolder(arg1:string):Promise<void>;

export function PauseRecording():Promise<void>;

export function PlayVideo(arg1:string):Promise<void>;

export function ResumeRecording():Promise<void>;

export function SelectOutputDir():Promise<string>;

export function StartRecording(arg1:backend.RecordConfig):Promise<void>;

export function StopRecording():Promise<string>;

export function TogglePauseResume():Promise<string>;
